### ISSUE TITLE
Improve on false negatives

### ISSUE THREAD

**Issue by parro-it** [brrd/electron-is-accelerator#3]
Posted on behalf of @MarshallOfSound. As he did wrote [here](https://github.com/sindresorhus/awesome-electron/pull/387):

> @brrd I had a quick play around and although it appears to be useful (I have user defined shortcuts) it appears to be incorrect.
> For instance
> require("electron-is-accelerator")("A+Control") // false
> That is a valid accelerator and should return true. Also appears to not be able to run in a Node.JS 4.x environment due to missing 'use strict' declarations.

**Comment by brrd** [comment]
I thought this was not valid but I just tried it and it works actually.

**Comment by parro-it** [comment]
Any news about this?

**Comment by djalmaaraujo** [comment]
Would be great to know, I am getting:
Ctrl+left, ctrl+right, Command+left, Command+right as invalid accelerators too.

**Comment by djalmaaraujo** [comment]
```bash
WARNING: Ctrl+left is not a valid accelerator.

    at WebContents.<anonymous> (/Users/z/zz/zzz/zzz-electron/app.js:63:15)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:96:13)
    at WebContents.emit (events.js:188:7)


WARNING: Command+left is not a valid accelerator.

    at WebContents.<anonymous> (/Users/z/zz/zzz/zzz-electron/app.js:63:15)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:96:13)
    at WebContents.emit (events.js:188:7)


WARNING: Command+right is not a valid accelerator.

    at WebContents.<anonymous> (/Users/z/zz/zzz/zzz-electron/app.js:63:15)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:96:13)
    at WebContents.emit (events.js:188:7)


WARNING: Ctrl+right is not a valid accelerator.

    at WebContents.<anonymous> (/Users/z/zz/zzz/zzz-electron/app.js:63:15)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:96:13)
    at WebContents.emit (events.js:188:7)
```

**Comment by brrd** [comment]
@djalmaaraujo This is not directly related to this thread. Please create a new issue.
